using System;

DateTime data1 = new DateTime();
Console.WriteLine(data1);
DateTime data2 = DateTime.Now;
Console.WriteLine(data2);
DateTime data3 = new DateTime(2025,11,21);
Console.WriteLine(data3);
DateTime data4 = new DateTime(2025, 11, 21,23,22,45);
Console.WriteLine(data4);
Console.WriteLine(DateTime.Now);
Console.WriteLine(DateTime.UtcNow);
Console.WriteLine(DateTime.Today);
Console.WriteLine(data2.Year);
Console.WriteLine(data2.Month);
Console.WriteLine(data2.Day);
Console.WriteLine(data2.Hour);
Console.WriteLine(data2.Minute);
Console.WriteLine(data2.Second);
Console.WriteLine(data2.Millisecond);
Console.WriteLine(DateTime.MinValue);
Console.WriteLine(DateTime.MaxValue);
Console.WriteLine(data2.Microsecond);
Console.WriteLine(data2.Nanosecond);
Console.WriteLine(data2.Kind);
DateTime data5 = DateTime.Parse("2025-12-3");
Console.WriteLine(data5.Add(new TimeSpan(4,5,6,45)));
Console.WriteLine(data5.AddDays(7));
Console.WriteLine(data5.AddDays(-3));
Console.WriteLine(data5.AddHours(67));
Console.WriteLine(data5.AddTicks(7803453453553));
Console.WriteLine(data5.Subtract(DateTime.Now));
Console.WriteLine(data5.CompareTo(data4));
Console.WriteLine(data5==DateTime.Now);
Console.WriteLine(data5.Day);
Console.WriteLine(data5.DayOfWeek);
Console.WriteLine(data5.DayOfYear);
Console.WriteLine(data2.ToLocalTime());
Console.WriteLine(data2.ToUniversalTime());
Console.WriteLine(data2.ToLongDateString());
Console.WriteLine(data2.ToShortDateString());
Console.WriteLine(data2.ToLongTimeString());
Console.WriteLine(data2.ToShortTimeString());

//дата и время во всех форматах
Console.WriteLine($"D:{data2.ToString("D")}");//Полный формат даты. Например, 17 июля 2015 г.
Console.WriteLine($"d:{data2.ToString("d")}");
Console.WriteLine($"F:{data2.ToString("F")}");
Console.WriteLine($"f:{data2.ToString("f")}");
Console.WriteLine($"G:{data2:G}");
Console.WriteLine($"g:{data2:g}");
Console.WriteLine($"M:{data2:M}");
Console.WriteLine($"O:{data2:O}");
Console.WriteLine($"o:{data2:o}");
Console.WriteLine($"R:{data2:R}");
Console.WriteLine($"s:{data2:s}");
Console.WriteLine($"T:{data2:T}");
Console.WriteLine($"t:{data2:t}");
Console.WriteLine($"U:{data2:U}");
Console.WriteLine($"u:{data2:u}");
Console.WriteLine($"Y:{data2:Y}");
Console.WriteLine(data2.ToString("yyyy-MM-dd hh:mm:ss"));
//DateOnly
DateOnly d1=DateOnly.FromDateTime(DateTime.Now);
Console.WriteLine(d1);
DateOnly d2 = new DateOnly();
Console.WriteLine(d2);
DateOnly d3=new DateOnly(2025,12,3);
Console.WriteLine(d3);
Console.WriteLine(d2.Year);
Console.WriteLine(d2.Month);
Console.WriteLine(d2.Day);
Console.WriteLine(d3.DayNumber);
Console.WriteLine(d3.DayOfWeek);
Console.WriteLine(d3.DayOfYear);
Console.WriteLine(DateOnly.MinValue);
Console.WriteLine(DateOnly.MaxValue);
Console.WriteLine(d2.ToLongDateString());
Console.WriteLine(d3.ToShortDateString());
//TimeOnly
TimeOnly time1 = new TimeOnly();
Console.WriteLine(time1);
TimeOnly time2 = TimeOnly.FromDateTime(DateTime.Now);
Console.WriteLine(time2);
Console.WriteLine(time2.Hour);
Console.WriteLine(time2.Minute);
Console.WriteLine(time2.Second);
Console.WriteLine(time2.Ticks);

